runner:
  total_steps: 10000
  gradient_clipping: 1
  gradient_accumulate_steps: 8

  log_step: 250
  eval_step: 250
  save_step: 250
  max_keep: 1
  eval_dataloaders:
    - dev
    - test

optimizer:
  name: Adam
  lr: 1.0e-4

# comment the whole scheduler config block
# to disable learning rate scheduling
#scheduler:
#  name: linear_schedule_with_warmup
#  num_warmup_steps: 1500

downstream_expert:
  datarc:
    data_dir: /data/EmoFilm/wav_corpus_16k
    label_path: ./downstream/emofilm-cv/fold_3.csv
    # test_fold: fold1
    num_class: 5  
    num_workers: 20
    train_batch_size: 2
    eval_batch_size: 2

  modelrc:
    input_dim: 128
