# All hyper-parameters taken from the official implementation at
# https://github.com/Alexander-H-Liu/NPC/blob/main/config/self_supervised/npc_example.yml

runner:
  n_epochs: 100
  total_steps: -1
  gradient_clipping: 5.0
  gradient_accumulate_steps: 1

  log_step: 2500
  save_step: 2500
  max_keep: 5
  
  fp16: false

optimizer:
  name: Adam
  lr: 0.001

pretrain_expert:
  datarc:
    num_workers: 8
    train_batch_size: 32
    max_timestep: -200 # Max length for audio feature (0 for no restriction, negative value to set minimum timestep)
    libri_root: '/media/andi611/1TBSSD/LibriSpeech/' # If raw libri data is provided, use on-the-fly feature extraction, else use the pre-extracted features under `file_path`
    file_path: 'data/len_for_bucket' # Pre-extracted features path. When using on-the-fly feature extraction, this is used to provide length for bucketing.
    sets: ['train-clean-100', 'train-clean-360', 'train-other-500'] # can be the subset of ['train-clean-100', 'train-clean-360', 'train-other-500']