runner:
  total_steps: 30000
  gradient_clipping: 1
  gradient_accumulate_steps: 8

  log_step: 250
  eval_step: 500
  save_step: 500
  max_keep: 5
  eval_dataloaders:
    - dev
    - test

optimizer:
  name: TorchOptim
  torch_optim_name: Adam
  lr: 1.0e-4

# comment the whole scheduler config block
# to disable learning rate scheduling
scheduler:
  name: linear_schedule_with_warmup
  num_warmup_steps: 1400

downstream_expert:
  datarc:
    root: /data/jtes_v1.1/jtes_aug/
    test_fold: fold1
    pre_load: True
    train_batch_size: 4
    eval_batch_size: 4
    num_workers: 10
    valid_ratio: 0.2

  modelrc:
    projector_dim: 256
    select: UtteranceLevel

    UtteranceLevel:
      pooling: MeanPooling

    DeepModel:
      model_type: CNNSelfAttention
      hidden_dim: 160
      kernel_size: 10
      padding: 4
      pooling: 10
      dropout: 0.5